### ISSUE TITLE
Unable to start corosync on pks cluster.

### ISSUE THREAD

**Issue by treyormsbee-interop** [Nexenta/edgefs#510] opened 2020-02-24 20:44 UTC
### Summary 

After creating a rook-edgefs cluster the corosync pods do not start with logs:

$ kubectl logs rook-edgefs-target-0 -n rook-edgefs -c corosync
Running in container

Node configuration is missing

Ive looked through all the scripts,  I am not sure where the message 'Node configuration is missing' is coming from.

### Steps to reproduce the behavior

Build a pks cluster,  deploy rook-operater and cluster.

### Expected behavior

corosync should start.

### Actual behavior

Corosync does not start.

### EdgeFS version

1.2.167.

### Deployment type

- [ x] Kubernetes with Rook Operator
- [ ] Docker Compose

- [x] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [x ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

PKS  1.4. with pks create.

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [x ] Ubuntu 18.04.x
- [ ] Other

**Comment by treyormsbee-interop** [comment] 2020-02-24 22:04
Small update,  I made another image and enabled -x on edgefs-startup.sh  and the failure happens here:

Running in container
+ export CCOW_LOG_STDOUT=1
+ CCOW_LOG_STDOUT=1
+ is_target_initial_population=0
+ test -e /opt/nedge/etc/ccow
+ test -e /opt/nedge/var/lock
+ test -e /opt/nedge/etc.target
+ test xcorosync = xconfig
+ test -e /opt/nedge/etc/ccow/ccow.json
+ test x '!=' x -a x10.100.200.1 '!=' x
+ case $1 in
+ shift
+ corosync_pre
+ mkdir -p /opt/nedge/var/run/corosync
+ mkdir -p /opt/nedge/var/log/cluster
+ test -e /opt/nedge/etc/config/nesetup.json
+ efscli config file /opt/nedge/etc/config/nesetup.json

Node configuration is missing
+ exit 1



I dont have an /opt/nedge/etc/config/ directory at all,  what creates that?

**Comment by dyusupov** [comment] 2020-02-24 22:06
operator mounts config map volume into it. Make sure that /var/lib/edgefs does not exists prior to creation of a cluster on all the hosts.

**Comment by treyormsbee-interop** [comment] 2020-02-24 22:25
Ok,  i deleted the cluster, wiped the directories on the host,  (/var/vcap/store/rook-{settings,data})  and apply the cluster config again.  This time i do have a .etc/config directory,   but... It's empty.  I also have the same error for corosync,  so it appears nesetup.json is not being created.  What creates that file?

**Comment by dyusupov** [comment] 2020-02-24 22:28
operator creates config map, you should see it in rook-edgefs-system namespace

**Comment by dyusupov** [comment] 2020-02-24 22:30
ah, no, in rook-edgefs cluster namespace, according to - https://github.com/rook/rook/blob/master/pkg/operator/edgefs/cluster/configmap.go

**Comment by treyormsbee-interop** [comment] 2020-02-24 22:42
Ahh,   so it's a configmap I have the configmap but it does not appear to be mounted in the corosync container.  Ill post the output in just a bit from the pod showing that.

**Comment by treyormsbee-interop** [comment] 2020-02-25 15:18
So this is the volumes for the pod:

  volumes:
  - hostPath:
      path: /dev
      type: ""
    name: devices
  - hostPath:
      path: /sys
      type: ""
    name: sys
  - hostPath:
      path: /run/udev
      type: ""
    name: udev
  - hostPath:
      path: /var/vcap/store/rook-settings
      type: DirectoryOrCreate
    name: edgefs-datadir
  - hostPath:
      path: /var/vcap/store/rook-data
      type: DirectoryOrCreate
    name: rook-data
  - configMap:
      defaultMode: 420
      items:
      - key: nesetup
        path: nesetup.json
      name: edgefs-config
    name: edgefs-configdir
  - name: rook-edgefs-cluster-token-8kp6z
    secret:
      defaultMode: 420
      secretName: rook-edgefs-cluster-token-8kp6z


And for corosyn this it the mounts.

**Comment by treyormsbee-interop** [comment] 2020-02-25 22:26
Sorry for the long delay,  I added a little more debugging to edgefs-startup.sh to see what was going on,  The nessetup.json file is located here:

/opt/nedge/etc/config/..2020_02_25_22_20_08.786736029/nesetup.json

i have no idea where the ..2020_02_25_22_20_08.786736029 is coming from?  Any ideas?

Im sure I can overcome that by modifying edgefs-start.sh,  but if anyone knows where that is coming from it would help.

**Comment by dyusupov** [comment] 2020-02-25 22:36
ah, I think the issue is with PKS and use of subPath for volumes. I believe this issue is where we need to focus on - https://github.com/rook/rook/issues/3958. I would appreciate if someone could take a deeper look and send us some preliminary fix. Closing this in favor of rook issue.

**Closed by dyusupov** 2020-02-25 22:36 UTC
Labels: bug

**Comment by treyormsbee-interop** [comment] 2020-02-26 15:06
I did some more digging,  I think this should might need to be pulled back here,  my find command was flawed,  there is a synlink from that nesetup.json to the correct path.

root@rook-edgefs-target-4:/opt/nedge/sbin# LD_LIBRARY_PATH=/opt/nedge/lib ./efscli config file $NEDGE_HOME/etc/config/nesetup.json 

Node configuration is missing
root@rook-edgefs-target-4:/opt/nedge/sbin# LD_LIBRARY_PATH=/opt/nedge/lib ./efscli config file $NEDGE_HOME/etc/config/nesetup
Error reading JSON config file: Can't open json file /opt/nedge/etc/config/nesetup. open /opt/nedge/etc/config/nesetup: no such file or directoryroot@rook-edgefs-target-4:/opt/nedge/sbin# 


I now think it is the content of nesetup.json that is the problem.

Here is the formatetd content of the file:
{
  "10.215.7.5": {
    "ccow": {
      "trlog": {
        "interval": 10
      },
      "tenant": {
        "failure_domain": 1,
        "sync_put_named": 0,
        "sync_put_commit_wait": 1
      },
      "network": {
        "broker_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      }
    },
    "ccowd": {
      "repdev_bg_config": {
        "trlog_delete_after_hours": 72,
        "speculative_backref_timeout": 259200000
      },
      "network": {
        "server_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      },
      "transport": [
        "rtlfs"
      ]
    },
    "auditd": {
      "is_aggregator": 0
    },
    "ipv4_autodetect": 1,
    "cluster_nodes": [
      "rook-edgefs-target-0.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-1.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-2.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-3.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-4.rook-edgefs-target.rook-edgefs"
    ],
    "rtrd": {
      "devices": []
    },
    "rtrdslaves": [],
    "rtlfs": {
      "devices": [
        {
          "name": "rook-data",
          "path": "/var/vcap/store/rook-data",
          "psize": 16384,
          "verify_chid": 1,
          "check_mountpoint": 0,
          "sync": 1
        }
      ]
    },
    "rtkvs": {
      "backend": "",
      "devices": null
    },
    "nodeType": "target"
  },
  "10.215.7.6": {
    "ccow": {
      "trlog": {
        "interval": 10
      },
      "tenant": {
        "failure_domain": 1,
        "sync_put_named": 0,
        "sync_put_commit_wait": 1
      },
      "network": {
        "broker_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      }
    },
    "ccowd": {
      "repdev_bg_config": {
        "trlog_delete_after_hours": 72,
        "speculative_backref_timeout": 259200000
      },
      "network": {
        "server_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      },
      "transport": [
        "rtlfs"
      ]
    },
    "auditd": {
      "is_aggregator": 0
    },
    "ipv4_autodetect": 1,
    "cluster_nodes": [
      "rook-edgefs-target-0.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-1.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-2.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-3.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-4.rook-edgefs-target.rook-edgefs"
    ],
    "rtrd": {
      "devices": []
    },
    "rtrdslaves": [],
    "rtlfs": {
      "devices": [
        {
          "name": "rook-data",
          "path": "/var/vcap/store/rook-data",
          "psize": 16384,
          "verify_chid": 1,
          "check_mountpoint": 0,
          "sync": 1
        }
      ]
    },
    "rtkvs": {
      "backend": "",
      "devices": null
    },
    "nodeType": "target"
  },
  "10.215.7.7": {
    "ccow": {
      "trlog": {
        "interval": 10
      },
      "tenant": {
        "failure_domain": 1,
        "sync_put_named": 0,
        "sync_put_commit_wait": 1
      },
      "network": {
        "broker_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      }
    },
    "ccowd": {
      "repdev_bg_config": {
        "trlog_delete_after_hours": 72,
        "speculative_backref_timeout": 259200000
      },
      "network": {
        "server_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      },
      "transport": [
        "rtlfs"
      ]
    },
    "auditd": {
      "is_aggregator": 0
    },
    "ipv4_autodetect": 1,
    "cluster_nodes": [
      "rook-edgefs-target-0.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-1.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-2.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-3.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-4.rook-edgefs-target.rook-edgefs"
    ],
    "rtrd": {
      "devices": []
    },
    "rtrdslaves": [],
    "rtlfs": {
      "devices": [
        {
          "name": "rook-data",
          "path": "/var/vcap/store/rook-data",
          "psize": 16384,
          "verify_chid": 1,
          "check_mountpoint": 0,
          "sync": 1
        }
      ]
    },
    "rtkvs": {
      "backend": "",
      "devices": null
    },
    "nodeType": "target"
  },
  "10.215.7.8": {
    "ccow": {
      "trlog": {
        "interval": 10
      },
      "tenant": {
        "failure_domain": 1,
        "sync_put_named": 0,
        "sync_put_commit_wait": 1
      },
      "network": {
        "broker_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      }
    },
    "ccowd": {
      "repdev_bg_config": {
        "trlog_delete_after_hours": 72,
        "speculative_backref_timeout": 259200000
      },
      "network": {
        "server_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      },
      "transport": [
        "rtlfs"
      ]
    },
    "auditd": {
      "is_aggregator": 0
    },
    "ipv4_autodetect": 1,
    "cluster_nodes": [
      "rook-edgefs-target-0.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-1.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-2.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-3.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-4.rook-edgefs-target.rook-edgefs"
    ],
    "rtrd": {
      "devices": []
    },
    "rtrdslaves": [],
    "rtlfs": {
      "devices": [
        {
          "name": "rook-data",
          "path": "/var/vcap/store/rook-data",
          "psize": 16384,
          "verify_chid": 1,
          "check_mountpoint": 0,
          "sync": 1
        }
      ]
    },
    "rtkvs": {
      "backend": "",
      "devices": null
    },
    "nodeType": "target"
  },
  "10.215.7.9": {
    "ccow": {
      "trlog": {
        "interval": 10
      },
      "tenant": {
        "failure_domain": 1,
        "sync_put_named": 0,
        "sync_put_commit_wait": 1
      },
      "network": {
        "broker_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      }
    },
    "ccowd": {
      "repdev_bg_config": {
        "trlog_delete_after_hours": 72,
        "speculative_backref_timeout": 259200000
      },
      "network": {
        "server_interfaces": "eth0",
        "server_unix_socket": "/opt/nedge/var/run/sock/ccowd.sock"
      },
      "transport": [
        "rtlfs"
      ]
    },
    "auditd": {
      "is_aggregator": 0
    },
    "ipv4_autodetect": 1,
    "cluster_nodes": [
      "rook-edgefs-target-0.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-1.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-2.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-3.rook-edgefs-target.rook-edgefs",
      "rook-edgefs-target-4.rook-edgefs-target.rook-edgefs"
    ],
    "rtrd": {
      "devices": []
    },
    "rtrdslaves": [],
    "rtlfs": {
      "devices": [
        {
          "name": "rook-data",
          "path": "/var/vcap/store/rook-data",
          "psize": 16384,
          "verify_chid": 1,
          "check_mountpoint": 0,
          "sync": 1
        }
      ]
    },
    "rtkvs": {
      "backend": "",
      "devices": null
    },
    "nodeType": "target"
  }
}



Are my pods supposed to be using the hostnetwork?  I think that might be my problem if so, as in pks enterprise you cannot use hostnetworks.

**Comment by dyusupov** [comment] 2020-02-26 16:23
hostnetwork isn't needed. Can you check if hostnames of your nodes can be DNS resolved? For some reason operator uses IP addresses instead of DNS names while referencing node structures, e.g. "10.215.7.9" etc...

**Comment by treyormsbee-interop** [comment] 2020-02-26 17:00
Let me get back to you on that one,  pks sets the hosts hostname to the ip address.  The ip addresses in those files are the ip addresses of each host.

**Comment by treyormsbee-interop** [comment] 2020-02-26 18:17
Ok  I changed the hostnames in the cluster to resolvable dns names,  but I am getting the same from the efscli config file,  command that node configuration is missing.

so after I bit of looking at the src code,  I think i found the problem.  config.go uses the following to match the hostname 

  if nodename == "" {
    host_hostname := os.Getenv("HOST_HOSTNAME")

    var hostname string
    if host_hostname != "" {
      hostname = host_hostname
    } else {
      var err error
      hostname, err = os.Hostname()
      if err != nil {
        fmt.Printf("Error resolving local hostname: %s\n", err)
        os.Exit(1)
      }
    }
    nodename = hostname
  }


then it calls the config file with this   nodeConfig = clusterConfig[nodename]

No matter what I set the kubernetes hostname to,  HOST_HOSTNAME is uuid.

But... If I deploy the cluster using the uuid's for the hostnames the cluster does not deploy,  It gets an Error stating the following: 

Status:
  Message:  giving up creating cluster in namespace rook-edgefs after 5m0s. Error: Node '21520ba3-bf9a-476b-8f09-a0a6cad7c7dd' is NOT valid. Check node status.
  State:    Error
Events:     <none>


so I think this is probably rook,  edgefs-cluster crd issue.

**Comment by treyormsbee-interop** [comment] 2020-02-26 18:31
Just to add,  for anyone else having this problem on a pks cluster,  the rook edgefs crd says you have to use the kubernetes.io/hostname label for you node name,  but the pods are deployed with this environment 

    Environment:
      HOST_HOSTNAME:   (v1:spec.nodeName)
      K8S_NAMESPACE:  rook-edgefs

nodeName and kubernetes.io/hostname are not the same.

**Comment by treyormsbee-interop** [comment] 2020-02-26 18:51
one last note,  I was able to change kubernetes.io/hostname to match node name on each host.  And was able to get everything started up.  I think I will open a ticket with pks enterprise on why those dont match... to ensure I dont break anything by doing that.
